### ISSUE TITLE
Fix: Make validations ordered

### ISSUE THREAD

**Issue by jbutlerdev** [mule-ai/mule#17]
# Story

As a workflow developer, I need validations to execute in a predictable, ordered sequence to ensure dependencies between validations are properly handled.

# Background

Currently, validations may execute in undefined order, causing issues when:
- One validation depends on the output of another
- Early validations could prevent expensive later validations
- Validation results need to be aggregated in sequence
- Critical validations should fail fast

# Acceptance Criteria

## Ordering Mechanism
- [ ] **Priority-based ordering** (numeric priority values)
- [ ] **Dependency declaration** (validation A requires B)
- [ ] **Stage-based grouping** (pre-checks, main, post-checks)
- [ ] **Fail-fast option** for critical validations
- [ ] **Parallel execution** within same priority level

## Configuration
- [ ] **Default priority** for unspecified validations
- [ ] **Override capability** at workflow level
- [ ] **Visualization** of validation execution order
- [ ] **Cycle detection** for circular dependencies

# Technical Implementation

## Priority-Based System

```yaml
validations:
  - name: "check-permissions"
    priority: 100  # Highest priority, runs first
    fail_fast: true
    
  - name: "validate-syntax"
    priority: 90
    
  - name: "run-tests"
    priority: 50
    depends_on: ["validate-syntax"]
    
  - name: "check-coverage"
    priority: 40
    depends_on: ["run-tests"]
    
  - name: "security-scan"
    priority: 30
    parallel: true  # Can run with same priority items
```

## Execution Stages

```yaml
validation_stages:
  pre_checks:
    - authentication
    - permissions
    - rate_limits
    
  main_validations:
    - syntax_check
    - type_check
    - unit_tests
    
  post_validations:
    - coverage_report
    - performance_metrics
    - notifications
```

## Dependency Resolution

```typescript
class ValidationScheduler {
  private buildExecutionOrder(validations: Validation[]): Validation[] {
    // Topological sort with priority consideration
    const graph = this.buildDependencyGraph(validations);
    const sorted = this.topologicalSort(graph);
    return this.groupByPriority(sorted);
  }
  
  private detectCycles(graph: DependencyGraph): boolean {
    // DFS-based cycle detection
    return this.hasCycle(graph);
  }
}
```

## Execution Flow

1. **Parse Configuration**: Load validation definitions
2. **Build Dependency Graph**: Create DAG of validations
3. **Detect Cycles**: Ensure no circular dependencies
4. **Sort by Priority**: Order validations by priority
5. **Execute in Stages**: Run validations according to order
6. **Handle Failures**: Stop on fail_fast or continue

# Configuration Examples

## Simple Priority
```yaml
validations:
  order: priority  # or "dependency", "manual"
  fail_fast: false
  items:
    - name: auth_check
      priority: 1000
    - name: lint
      priority: 500
    - name: test
      priority: 100
```

## Dependency-Based
```yaml
validations:
  order: dependency
  items:
    - name: compile
      depends_on: []
    - name: test
      depends_on: [compile]
    - name: coverage
      depends_on: [test]
```

## Hybrid Approach
```yaml
validations:
  order: hybrid
  stages:
    - name: critical
      fail_fast: true
      validations: [auth, permissions]
    - name: quality
      parallel: true
      validations: [lint, format, spell]
    - name: testing
      validations: [unit, integration, e2e]
```

# Backward Compatibility

- Default behavior maintains current (unordered) execution
- Opt-in to ordered execution via configuration
- Migration tool to analyze existing validations
- Warning system for potential ordering issues

# Priority: Medium
# Target: Q1 2026
# Impact: Reliability, Performance, Developer Experience
