### ISSUE TITLE
Feature: Event based actions

### ISSUE THREAD

**Issue by jbutlerdev** [mule-ai/mule#70]
# Story

As a user, I want Mule to respond to events in real-time rather than relying on polling, so that workflows can be triggered instantly when conditions change.

# Background

Currently, Mule uses polling mechanisms to check for changes, which introduces latency and increases resource usage. An event-based system would provide:
- Instant response to changes
- Reduced system overhead  
- Better scalability
- More responsive user experience

# Acceptance Criteria

## Webhook Support
- [ ] Generic webhook endpoint for receiving external events
- [ ] GitHub webhook integration for repository events
- [ ] Custom webhook authentication and validation
- [ ] Webhook payload transformation and routing

## Supabase Integration
- [ ] Real-time database change listeners
- [ ] Row-level security for event subscriptions
- [ ] Connection pooling and error handling
- [ ] Event filtering and routing logic

## Event Schema & Processing
- [ ] Standardized event schema definition
- [ ] Event validation and sanitization
- [ ] Event routing to appropriate workflows
- [ ] Event history and audit logging

## Migration from Polling
- [ ] Identify current polling mechanisms
- [ ] Create migration path for existing workflows
- [ ] Backward compatibility during transition
- [ ] Performance comparison and optimization

# Technical Implementation

## Webhook Infrastructure
- HTTP endpoint: `/webhooks/{source}/{event-type}`
- Authentication: HMAC signature validation
- Rate limiting and abuse prevention
- Async event processing queue

## Event Processing Pipeline
```
Incoming Event -> Validation -> Transformation -> Routing -> Workflow Trigger
```

## Configuration Example
```yaml
events:
  webhooks:
    github:
      secret: ${GITHUB_WEBHOOK_SECRET}
      events: [push, pull_request, issues]
    custom:
      auth_type: bearer_token
      token: ${CUSTOM_WEBHOOK_TOKEN}
  supabase:
    enabled: true
    tables: [workflows, agents, repositories]
    events: [insert, update, delete]
```

# API Endpoints

- `POST /webhooks/github` - GitHub event receiver
- `POST /webhooks/custom/{id}` - Custom webhook receiver  
- `GET /events/history` - Event history and logs
- `POST /events/replay/{id}` - Replay specific event

# Priority: High
# Target: Q4 2025
# Impact: Performance, User Experience, Scalability
